version: "3.1"

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: postgres_adminer
    ports:
      - 8080:8080