version: "3.1"

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: typescript_db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: postgres_adminer
    ports:
      - 8080:8080